### PR TITLE
Reduce font size of ol / ul tags on article pages

### PR DESCRIPTION
**Pull request by kaladin9017**
#### What's this PR do?
Fix bug causing large ordered list numbers being cut off on safari mobile views.

#### How was this tested? How should this be reviewed?
Reviewed using Chrome dev tools and Safari responsive development views.
 
#### What are the relevant tickets?
#80 

#### Questions / Considerations
n/a

### CODE REVIEW

**Comment by jonuy** [comment]
The drop in font size itself does seem to bring it back into the viewport. But the difference in horizontal alignment seems even more pronounced now. What do you think about maybe removing the top and left margins on the `p` element in ol/ul lists?

screen shot 2017-08-09 at 3 59 24 pm

**Comment by kaladin9017** [comment]
Could you point to the specific screen width that occurs at?

**Comment by jonuy** [comment]
Ah yea, I had to do a bit of searching before I found the article the GH issue was referencing. Looks like it's this one: https://advice.shinetext.com/articles/new-study-says-to-have-fun-first-work-later/

**Comment by kaladin9017** [comment]
Sorry, I should have been more specific. I meant the width you saw the alignment start to look off or which browser?

**Comment by jonuy** [comment]
Oh my bad, I misunderstood. I'm seeing it in both Safari and Chrome.

screen shot 2017-08-09 at 4 50 10 pm
https://deploy-preview-103--shine-advice-production.netlify.com/articles/new-study-says-to-have-fun-first-work-later/

I'd expect either the bottom of the big font and the bottom of the first line of the smaller font to align, or for them both to be top-aligned.

**Comment by jonuy** [comment]
That does look better. It seems to create some extra space though between the first and second lines of the paragraphs though -- I think it's related to the larger font size of the item numbers.

I should've before, but I went back to look at the figma design:

screen shot 2017-08-09 at 6 32 44 pm

and it looks like it keeps the top aligned. I think we can achieve it here by keeping `display: inline-block` but then removing the top margin on the paragraph elements in the list items. And from trying it out in my dev tools at least, it seems to also not mess with the line spacing.

**Comment by kaladin9017** [comment]
Thanks for the advice. Removing the top margin works perfect for alignment. My only concern about doing that is it reduced the space between paragraphs a little bit and it became a little harder to clearly see the next paragraph. Maybe if I add some margin to the ``` <li> ``` tags?

**Comment by jonuy** [comment]
Hmmm yea I see what you're saying. The margins between the `<li>` elements is the same (20px) as what's between regular `<p>` elements though. So I think numbers wise it matches up with the rest of the page and I think personally it looks fine.

@marahml Could you check the numbered list on this page and let us know what you thin?
 https://deploy-preview-103--shine-advice-production.netlify.com/articles/new-study-says-to-have-fun-first-work-later/

**Pull request merged**
