### PR TITLE
add static shine-squad info to template

### PR DESCRIPTION
**Pull request by kaladin9017**
#### What's this PR do?
Adds the static information about shine squad members to the homepage template

#### How was this tested? How should this be reviewed?
Ngrok and chrome dev tools

#### Questions / Considerations
Not sure if the links will work properly pointing to http when we switch over to netlify.

### CODE REVIEW

**Comment by jonuy** [comment]
Cool. I think it all looks fine. I want to make sure the links are gonna work though after the flip though and I'm not sure they will right now. Like if you go to:
- http://advice-staging.shinetext.com/articles/how-this-shine-squad-member-stopped-comparing-himself-to-others
- http://advice-staging.shinetext.com/articles/shine-squad-feature-ninas-4-tips-to-slow-down-and-enjoy-life/

They don't seem to be there. Any ideas what might be the issue there?

**Comment by jonuy** [comment]
Oh I think I've got a solution to the URL thing. I'll post in a separate PR.

Before pushing this one up, what do you think about removing the `By` next to the author name here too? Partly for consistency. But also can seem kinda confusing where the testimonial part can then look like the article title. Maybe enclosing the testimonial in quotes too could help with that?

screen shot 2017-07-03 at 4 01 11 pm

**Comment by kaladin9017** [comment]
@jonuy 
The slug is different on staging "/articles/shine-squad-feature-how-i-stopped-comparing-myself/" is the location. 

I checked contentful and the slug is different than on staging.

**Comment by kaladin9017** [comment]
I think its more consistent without By and I didn't hear any complaints from Marah or Kim about the other changes we made.

**Pull request merged**
