### PR TITLE
Optimizes font and social icon loading

### PR DESCRIPTION
**Pull request by jonuy**
#### What's this PR do?
Minor load time optimizations.
- Cleans up Google Font loading. Does it in one call and removes one we're not using
- Uses new Font Awesome implementation
- Loads social icons in the footer as a single sprite image instead of 4 separate ones

#### How was this tested?
Local testing + DevTools. Ultimately these changes seem pretty minor only saving maybe 100ms on average

### CODE REVIEW

**Comment by kaladin9017** [comment]
The mail icon click action isn't firing on mobile. Seeing "target is too small" in chrome debugger console.

**Comment by jonuy** [comment]
@kaladin9017 Were you not able to click on the icon at all? I've just tested from my local setup through both DevTools simulating a Galaxy S5 and then through my S8, and both cases worked. I did however also see the "target is too small" log in the console. But I'm getting that in production too.

**Comment by kaladin9017** [comment]
Yea, the mail worked in desktop view. When I tried in debug mode on a smaller screen size it wouldn't fire. It was a weird error. I'll try on my device.

**Comment by kaladin9017** [comment]
image
The mail icon works on my phone 🤷‍♂, but now the messenger icon is missing.

**Comment by jonuy** [comment]
@kaladin9017 Thanks for catching that! Just submitted the fix for the SMS share icon.

Screen Shot 2020-01-23 at 12 19 17 PM
.

**Pull request merged**
